### ISSUE TITLE
Problem getting X86 docker image using docker-compose

### ISSUE THREAD

**Issue by daserra23** [jollyjinx/sma2mqtt#2]
Hi, I created the following docker-compose.yml file but it seems to only download the arm64 image even though I am on X86, perhaps I need to specify something different.
`version: '3'

services:
  sma2mqtt:
    image: jollyjinx/sma2mqtt:latest
    container_name: sma2mqtt
    network_mode: "host"  # <-- This enables host networking
    environment:
      - INVERTER_PASSWORD=mYpASSWORD
    command: >
      sma2mqtt
      --mqtt-servername 192.168.2.31
      --mqtt-port 1883
      --basetopic sma2mqtt
      --inverter-password mYpASSWORD
    restart: unless-stopped
`
If I try to run the command in the readme without docker-compose I get the error "docker run --name "sma2mqtt" --net service16  jollyjinx/sma2mqtt:latest sma2mqtt --inverter-password mYpASSWORD
docker: Error response from daemon: network service16 not found.
"

**Comment by jollyjinx** [comment]
docker run --name "sma2mqtt" --net service16 jollyjinx/sma2mqtt:latest sma2mqtt --inverter-password mYpASSWORD

the option --net service16 is meant to run it on vlan service16 - which does not exist at your placy
try using --host instead

**Comment by jollyjinx** [comment]
I've fixed the intel image. Thank you for pointing out.

I'm using the following docker compose - be aware that I'm using VLANs and mqtt container so the networks might be different.
```
  sma2mqtt:
    <<: [*common-variables, *default-logging]
    container_name: sma2mqtt
    hostname: sma2mqtt
      #image: jollyjinx/sma2mqtt:latest
    image: jollyjinx/sma2mqtt:3.1.1
      #image: jollyjinx/sma2mqtt:development
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    command: sma2mqtt --inverter-password ${INVERTER_PASSWORD}
    networks:
      aservice1016:
        ipv4_address: ${NETWORK_PREFIX}.16.3
      mqtt-net: {}
    depends_on:
      - mqtt

```
